defmodule Qwynk.Repo.Migrations.AddLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:links, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slug, :text, null: false
      add :destination, :text, null: false
      add :strategy, :text, null: false, default: "temporary"
      add :is_active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "links_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:links, [:slug], name: "links_unique_slug_index")
  end

  def down do
    drop constraint(:links, "links_owner_id_fkey")

    drop_if_exists unique_index(:links, [:slug], name: "links_unique_slug_index")

    drop table(:links)
  end
end
