defmodule Qwynk.Repo.Migrations.AddAnalytics do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:daily_salts, primary_key: false) do
      add :date, :date, null: false, primary_key: true
      add :secret, :text, null: false
    end

    create unique_index(:daily_salts, [:date], name: "daily_salts_unique_date_index")

    create table(:hits, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :timestamp, :utc_datetime, null: false
      add :visitor_hash, :text, null: false
      add :country, :text
      add :device, :text
      add :referrer_domain, :text

      add :link_id,
          references(:links,
            column: :id,
            name: "hits_link_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:hits, [:link_id, :timestamp])

    create index(:hits, [:link_id, :visitor_hash])
  end

  def down do
    drop_if_exists index(:hits, [:link_id, :visitor_hash])

    drop_if_exists index(:hits, [:link_id, :timestamp])

    drop constraint(:hits, "hits_link_id_fkey")

    drop table(:hits)

    drop_if_exists unique_index(:daily_salts, [:date], name: "daily_salts_unique_date_index")

    drop table(:daily_salts)
  end
end
